config/routes.rb
Rails.application.routes.draw do
  get 'friendship/create'

  get 'friendship/destroy'

  resources :sessions, only: [:new, :create]
  resources :users do
  	resources :messages
  end
  delete '/logout' => 'sessions#destroy'
  get '/message/show' =>'messages#show'
  get '/show' => 'users#show'
  get '/sent' => 'users#sent'
  get '/alluser'	=> 'users#all_user'
  root "users#index"
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/message.rb
class Message < ApplicationRecord
	#attr_accessible :image, :remote_image_url
	belongs_to :sender, class_name: 'User'
	belongs_to :recipient, class_name: 'User'
	validates :title, presence: true
	validates :recipient_id, presence: true
	mount_uploader :image, AvatarUploader
	scope :unread, -> {where(read_at: nil)}

	def mark_as_read!
		self.read_at = Time.now
		save!
	end

	def read?
		read_at
	end
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true
	validates :email, presence: true, uniqueness: {case_insensitive: false}
	has_secure_password
	has_many :friendships
	has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user

	def received_messages
		Message.where(recipient_id: self)
	end

	def sent_messages
		Message.where(sender_id: self)
	end

	def lastest_received_messages(n)
		received_messages.order(created_at: :desc).limit(n)
	end

	def unread_messages
		received_messages.unread
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :signed_in?
  
  def current_user
  	return @current_user if @current_user
  	if session[:user_id]
  		@current_user = User.find(session[:user_id])
  	end
  end

  def signed_in?
  	if session[:user_id]
  		return true
  	else
  		return false
  	end
  end

  def require_login
  	unless signed_in?
  		flash[:errors] = "you must log in to access this section"
  		redirect_to new_session_path
  	end
  end
end

app/controllers/friendship_controller.rb
class FriendshipController < ApplicationController
  before_action :require_login, only: [:create]
  def create
  	@friendship = current_user.friendships.build(:friend_id => params[:friend_id])
  	if @friendship.save
  		flash[:notice] = "Added friend."
  		redirect_to alluser_path
  	else
  		flash[:error] = "Unable to add friend."
    	redirect_to root_path
  	end
  end

  def destroy
  	@friendship = current_user.friendships.find(params[:id])
  	@friendship.destroy
  	flash[:notice] = "Removed friendship."
    redirect_to alluser_path
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :require_login, only: [:new, :create]

	def new
		@user = current_user
		@users = current_user.friends
		@message = Message.new
	end
	def create
		@recipients = params[:message][:recipient_id]
		@title = params[:message][:title]
		@image = params[:message][:image]
		@recipients.each do |r|
		@message = current_user.sent_messages.build(:recipient_id => r, :title => @title, :image => @image)
		@message.save
		end
		if @message.errors.any?
			flash[:error] = "Can not create message, title and recipient can not empty"
			redirect_to new_user_message_path(current_user)
		else
			flash[:notice] = "create message success"
			redirect_to root_path
		end
	end

	def show
		@message = Message.find(params[:id])
		if !@message.read? && current_user == @message.recipient
			@message.mark_as_read!
			redirect_to show_path
		end
	end

	private
	def message_params
		params.require(:message).permit(:recipient_id, :title)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	if @user = User.find_by(email: params[:email])
  		if @user.authenticate(params[:password])
  			session[:user_id] = @user.id
  			redirect_to show_path, flash: {success: "Welcome back"}
  		else
  			redirect_to new_session_path, notice: "password is wrong"
  		end
  	else
  		redirect_to new_session_path, notice: "Email not found"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to new_session_path, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login, only: [:index, :show, :sent, :show_friend, :all_user]
	def index
		#@users = User.all
		@messages = current_user.lastest_received_messages(100)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new user_params
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path, notice: "Account created"
		else
			render "new"
		end
	end

	def user_params
		params.require(:user).permit(:name, :email, :password)
	end

	def show
		@messages = current_user.lastest_received_messages(100)
	end

	def sent
		@messages = current_user.sent_messages
	end

	def show_friend
		@friend_list = current_user.friends
	end

	def all_user
		@users = User.all.where.not(id: current_user.id)
	end

	def message_new
		@friend_list = current_user.friends
		@message = Message.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendship_helper.rb
module FriendshipHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendship/create.html.erb
<h1>Friendship#create</h1>
<p>Find me in app/views/friendship/create.html.erb</p>

app/views/friendship/destroy.html.erb
<h1>Friendship#destroy</h1>
<p>Find me in app/views/friendship/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PiChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-light bg-faded">
  		<a href="/" class="navbar-brand">PiChat</a>
  		<ul class="nav navbar-nav">
  			<% if current_user %>
  			<li class="nav-item">
  				<%= link_to "Log out #{current_user.email}", logout_path, method: 'delete', class: "nav-link" %>
  			</li>
  			<% else%>
  			<li class="nav-item">
  				<%= link_to "Create An Account", new_user_path, class: "nav-link" %>
  			</li>
  			<li class="nav-item">
  				<%= link_to "Log In", new_session_path, class: "nav-link" %>
  			</li>
  			<% end %>
  		</ul>
  	</nav>
  	<% unless flash.empty? %>
  		<% flash.each do |key,value|%>
  		<div class="alert alert-warning"><%= value %></div>
  		<% end %>
  	<% end %>

  	<div class="container">
  		
  		<%= yield %>	
  	</div>
    
  </body>
</html>

app/views/messages/new.html.erb
<h1>New message</h1>
<%= form_for [@user, @message], :html => {:multipart => true} do |f| %>
  <% unless @message.errors.empty? %>
    <div class="alert alert-danger">
      <%= @message.errors.full_messages.to_sentence %>
    </div>
  <% end %>
  <div class="form-group">
  	<%= f.label :recipient_id, class: "form-control-label" %>
  	<%= f.select(:recipient_id, @users.all.collect{|u| [u.name, u.id]}, {prompt: "Select friend"}, {:multiple => true, class: "form-control"})%>
  </div>
  <div class="form-group">
  	<%= f.label :title, class: "form-control-label" %>
  	<%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image, class: "form-control-label"%>
    <%= f.file_field :image, class: "form-control"%>
  </div>
  <div class="action">
  	<%= f.submit %>
  </div>
<% end %>

app/views/users/all_user.html.erb
<h1>All Users</h1>
<table class="table">
	<thead class="thead thead-default">
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Create at</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= user.name %></td>
			<td><%= user.email %></td>
			<td><%= time_ago_in_words user.created_at%></td>
			<% if current_user.friends.exists?(user) %>
			<td><%= link_to "Remove friend", friendship_destroy_path(:id => current_user.friendships.find_by_friend_id(user)), class: "btn btn-secondary" %></td>
			<% else %>
			<td><%= link_to "Add friend", friendship_create_path(:friend_id => user), :method => :get, class: "btn btn-secondary" %></td>
			<% end %>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/users/index.html.erb
<h1>Your message incoming</h1>
<%= link_to "New Message", new_user_message_path(current_user), class: "btn btn-secondary" %>
<%= link_to "Add Friends", alluser_path, class: "btn btn-secondary" %>
<%= link_to "Sent Messages", sent_path, class: "btn btn-secondary" %>
<div style="margin-top: 10px;">
	<table class="table">
	<thead class="thead thead-default">
		<th>Message</th>
		<th>Action</th>
	</thead>
	<tbody>
		<% @messages.each do |message| %>
		<tr>
			<% if message.read? %>
			<td><%= message.title %></td>
			<td>Already Read</td>
			<% else %>
			<td><b><%= message.title %></b></td>
			<td><%= link_to "Read", message_show_path(:id => message.id), class: "btn btn-secondary"%></td>
			<% end %>
			
		</tr>
		<% end %>
	</tbody>
	</table>
</div>

app/views/users/new.html.erb
<h1>Create an account</h1>

<%= form_for @user do |f| %>
	<% unless @user.errors.empty? %>
		<div class="alert alert-danger">
			<%= @user.errors.full_messages.to_sentence %>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, placeholder: "Full name please ...", class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :email %>
		<%= f.text_field :email, placeholder: "Enter your email...", class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :password %>
		<%= f.password_field :password, class: 'form-control' %>
	</div>
	<%= f.submit "Create Account", class: 'btn btn-secondary' %>
<% end %>

app/views/users/sent.html.erb
<h1>Sent Message</h1>
<div>
	<table class="table">
	<thead class="thead thead-default">
		<tr>
			<th>Message</th>
			<th>Image</th>
			<th>Time</th>
		</tr>
	</thead>
	<tbody>
		<% @messages.each do |message| %>
		<tr>
			<td><%= message.title %></td>
			<td><%= image_tag message.image_url.to_s if message.image? %></td>
			<% if message.read? %>
				<td><%= message.read_at.strftime("%d %m %Y %I:%M%p") %></td>
			<% else %>
				<td>unread</td>
			<% end %>
		</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/users/show.html.erb
<h1>Your message incoming</h1>
<%= link_to "New Message", new_user_message_path(current_user), class: "btn btn-secondary" %>
<%= link_to "Add Friends", alluser_path, class: "btn btn-secondary" %>
<%= link_to "Sent Messages", sent_path, class: "btn btn-secondary" %>
<div style="margin-top: 10px;">
	<table class="table">
	<thead class="thead thead-default">
		<th>Message</th>
		<th>Action</th>
	</thead>
	<tbody>
		<% @messages.each do |message| %>
		<tr>
			<% if message.read? %>
			<td><%= message.title %></td>
			<td>Already Read</td>
			<% else %>
			<td><b><%= message.title %></b></td>
			<td><%= link_to "Read", message_show_path(:id => message.id), class: "btn btn-secondary"%></td>
			<% end %>
			
		</tr>
		<% end %>
	</tbody>
	</table>
</div>